### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by astro** [tafia/quick-protobuf#1]
Please write some usage instructions. I would like to try your code with OpenStreetMap dumps.

**Comment by tafia** [comment]
Sure I'll do it today ! (This is very early stage of the library and while it may work for most use cases there may be some missing pieces, writing in particular is not yet implemented).

**Comment by tafia** [comment]
@astro I've just pushed a readme.

This is a very basic one, I plan to implements many missing features and have a much better documentation.

The is a high chance your openstreetmap files cannot be deserialized just yet. Let me know please your results and I'll fix it if necessary. Also I'm very interested in your feedback so I can improve the library. 

The library is just a week old ...

**Comment by astro** [comment]
Thank you very much!

**Comment by tafia** [comment]
You're welcome.

I'm very interested in your feedback, in particular if something is not working.

Also I advise you to point to a particular commit as the project is moving quite a lot and I cannot guarantee that the codegen you've created will always be aligned with the lib.

**Comment by tafia** [comment]
> the project is moving quite a lot

So today I made some breaking changes.

The `Message` trait has been renamed to `MessageRead` to be the counterpart of the new `MessageWrite` trait.

... which also means than we can write protobufs now 🎉 

I splited the 2 traits because eventually I will update the codegen tool to generate only the necessary traits.
