### ISSUE TITLE
Problem with Multiple Proto Files

### ISSUE THREAD

**Issue by stevedonovan** [tafia/quick-protobuf#48]
Looking good so far, but there's a hurdle to be jumped: when multiple proto files are defined, the lookup is ambiguous. Consider `package foo.one`  (by convention the filename would be `one.proto` but not necessarily.)  Say there's also packages `foo.two` and foo.three` and `foo.one` refers to messages in them. They are in a directory `test` - the full absolute crate path of anything in package `foo.one` is `::test::foo::mod_foo::mod_one`. For references in `one.rs` the strategy is to bring in `mod_foo` from `two` and `mod_foo` from `three`.  But `mod_foo` is a _nested_ module of `::test::foo::two` and a _different_ nested module of `::test::foo::three`. Hence the ambiguity!

One solution is always to emit full paths, like `::test::two::mod_foo::mod_two::Two`, and that would work. But the paths are starting to get ugly for human programmers!  So another solution is not to create those nested `mod_NAME` modules and instead rely on the usual rules. That is, the .rs files are created in a directory `foo`, and there's a generated `mod.rs` that refers to them. The full path would now be simply `::foo::two::Two`. (Without the `mod_` but with usual escaping rules for keywords) That's simple enough to be used directly in generated code.

I'm happy to work on a PR but this is a disruptive change, so I thought that some discussion is needed on the way forward.

**Comment by tafia** [comment]
Thanks for writing this. I too found the packages modules not nice to work with. 

Just to be sure we're on the same page you propose to ditch the packages inner modules and rely **only** on rust files modules, right? So the `::foo::two::Two` would become, if we follow the previous example, more a `::test::two::Two` (as there is no `foo` in filename) ?

Having full paths everywhere (the simplified version) does fix the ambiguity issue but I'm not sure it is the best solution as it makes refactoring very painful. Whenever you want to change your file hierarchy you need to regenerate all the files (provided pb-rs give you an option to prefix all these absolute paths), This can be inconvenient and problematic if you are not very careful that you're using exactly the same version of pb-rs,

So if possible, I'd like having relative paths using `super::` which still follow the usual rule: instead of using `Two` of `::test::two::Two` we could use `super::two::Two`.

The dev may not be that straightforward but if you feel brave enough I'll appreciate that!
The library is very young so I don't think this wil be too disruptive,

Do you see any issue in using the `super::` version?

**Comment by stevedonovan** [comment]
This makes complete sense. I did a quick hack to get `test:two::Two` with a `use super::super::*` and so the proposed scheme will work fine. It's all about counting those `super` s carefully!  So I'll go ahead - the other change is that pb-rs can be given multiple files, initially without caching (it's pretty fast).

**Comment by koivunej** [comment]
Hi and sorry for not noticing this earlier. @stevedonovan I've just submitted an PR on perhaps duplicated work, mainly adding `clap-rs` for command line parsing in [PR#50](https://github.com/tafia/quick-protobuf/pull/50) and a simple/hackish option to avoid adding the root package. I have no multi-file proto definitions in use, so I cannot test out how it could work.

Using `clap-rs` to get multiple `INPUT` files is no problem (see: [`Arg::multiple(..)`](https://docs.rs/clap/2.20.4/clap/struct.Arg.html#method.multiple), but I assume your current work goes deeper into `src/types.rs`, so hopefully there is not too much overlap.

**Comment by tafia** [comment]
@stevedonovan Is there anything I can do to help?
I really don't want to push you but I think I'll have (some) time next week.

**Comment by stevedonovan** [comment]
No problem! It's coming along nicely, should have a PR over the weekend. Just a number of corner cases - e..g _if_ there is an explicit package, that becomes the generated Rust file stem, and so forth. And automatically generating and updating a `mod.rs` file.

**Comment by tafia** [comment]
thanks a lot!

**Comment by stevedonovan** [comment]
Fiddly kind of filesystem stuff. I can't help thinking that there is a more elegant API hidden in Rust's filesystem handling, but that's a discussion for another day ;)

**Comment by stevedonovan** [comment]
Almost ready, I've cloned and made the changes. But I've added extra functionality (like specifying output directory and import search path) so I'd like to test it more thoroughly. Tomorrow for sure.

**Comment by tafia** [comment]
should we close this now?
