### ISSUE TITLE
Simplify codegen for MessageWrite

### ISSUE THREAD

**Issue by tafia** [tafia/quick-protobuf#5]
This is not a big deal but some lines tend to be very longs (in particular when working with packed fields).

As a start, we could rely on some new sizeofs.

**Comment by tafia** [comment]
At some point look at procedural macros (once stabilized) or directly serde ?

**Comment by tafia** [comment]
Another idea to future myself: as with the reader part, dropping the `MessageWrite` trait is a possibility if it proves to be to complicated to use (lifetimes etc ...)

**Comment by koivunej** [comment]
> Another idea to future myself: as with the reader part, dropping the MessageWrite trait is a possibility if it proves to be to complicated to use (lifetimes etc ...)

I just attempted to a:

```
trait AsMessageWrite<M: quick_protobuf::MessageWrite> {
     fn as_message_write(&self) -> M;
     
     fn decode<W: io::Write>(&self, out: &mut M) -> ::std::io::Error {
          let conv = self.as_message_write();
          conv.write_message(&mut quick_protobuf::writer::Writer::new(out)).map_err(convert_qp_err)
     }
}
```

While trying to implement this trait for one of my wrapper types I ran into trouble trying to use `Cow::Borrowed` fields and could not see any other choice than just clone and use `Cow::Owned`. I think that the issue is that `MessageWrite` does not have a lifetime specifier, which makes implementing the conversion impossible with borrowed fields.

If `MessageWrite` had an lifetime then there could be some issues with messages that own all their data. Though I cannot immediatedly see why they couldn't implement `MessageWrite<'static>`. Perhaps that needs to be prototyped.

**Comment by tafia** [comment]
I thought I answered that comment, sorry.
I have tried to put lifetime to `MessageWrite` (and the now removed `MessageRead`) but it didn't work. From my researches I cam to the conclusion that I needed Higher Kinded Types for this to work.
I'd be more than happy to be wrong!

**Comment by koivunej** [comment]
> From my researches I cam to the conclusion that I needed Higher Kinded Types for this to work.

This could very well be true, have to admit I'm not an expert on the topic. Perhaps I'll have time at some point to try this out myself as well.
