### ISSUE TITLE
proto3 repeated elements do not work

### ISSUE THREAD

**Issue by SergejJurecko** [tafia/quick-protobuf#99]
proto3 changes how repeated elements are serialized and quick-protobuf is incompatible. Is this a known issue?

**Comment by SergejJurecko** [comment]
I'm pretty sure this is the issue: https://developers.google.com/protocol-buffers/docs/encoding#packed

When using a different protocol buffers implementation server-side (erlang gpb) and specifying proto3 syntax, repeated types will not be packed by quick-protobuf and as a result will fail to deserialize on the server.

**Comment by tafia** [comment]
Could you please write a failing test for me?
Because the implementation looks right:

.proto file (packed per default)
https://github.com/tafia/quick-protobuf/blob/master/tests/rust_protobuf/v3/test_basic_pb.proto#L22-L25

codegen
https://github.com/tafia/quick-protobuf/blob/master/tests/rust_protobuf/v3/basic.rs#L180-L213

test
https://github.com/tafia/quick-protobuf/blob/master/tests/rust_protobuf/v3/test_basic.rs#L37-L51

**Comment by SergejJurecko** [comment]
I think the problem is that packing is used on non-primitive types.

````
syntax = "proto3";

message Embedded {
  int32 i = 1;
}

message WSMsg {
    repeated Embedded msgs = 1 [packed=true];
}
````

The above proto file will be considered invalid by protoc:
msg.proto:8:14: [packed = true] can only be specified for repeated primitive fields.

While it will compile fine with quick-protobuf/codegen
The resulting serialized data will be the same if packed=true or if packed modifier is not present. If packed is set to false, the binary data will be different and deserializable correctly with protoc --decode_raw

**Comment by SergejJurecko** [comment]
You can try it with: https://github.com/SergejJurecko/qptest/

cargo run
make check

or

make protoc
make check

**Comment by tafia** [comment]
That's interesting, thank you!

**Comment by tafia** [comment]
Close for #68
